### ISSUE TITLE
after entering key it says invalid key

### ISSUE THREAD

**Issue by ravigitgit** [MayankFawkes/Vyapam#1]
![Capture](https://user-images.githubusercontent.com/16426047/212256545-efd5aaab-219e-4a88-9f6c-6807a0ca553d.PNG)

**Comment by MayankFawkes** [comment]
this might because of dns problem, or you can just remove the trying function and run it directly.

try replacing the trying function to 

```
def trying():
	main("hey, Welcome")
```
